name: Deployment-to-Heroku

on:
  release:
    types: [created]

env:
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t natthaphonc01/php-docker-heroku:latest .
      
    - name: Verify Docker image exists locally
      run: docker images natthaphonc01/php-docker-heroku:latest
      
    - name: Push Docker image to Docker Hub
      run: docker push natthaphonc01/php-docker-heroku:latest
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: php-artifacts
        path: php-1
        
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: php-artifacts

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
      
    - name: Push Docker image to Heroku Container Registry
      run: heroku container:push web --app ${{ env.HEROKU_APP_NAME }}

    - name: Release the Docker image on Heroku
      run: heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
